version: "2"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
